### ISSUE TITLE
Option to force color

### ISSUE THREAD

**Issue by aste-mikkok** [ENT8R/package-age#2]
It would be nice to able to retain color output even when output is being redirected to pipe or file. I suggest adding an option `--color`, which when used sets `chalk.level` to appropriate value.

Great tool btw 👍

**Comment by ENT8R** [comment]
Thank you for your idea and the nice feedback 👍 I will release a new version which includes a `--color` and `--no-color` flag in a few minutes.

**Comment by ENT8R** [comment]
🔖v0.4.0 is now released on [npm](https://www.npmjs.com/package/package-age) 🎉
